# SPDX-FileCopyrightText: Copyright (c) 2025 Orange
# SPDX-License-Identifier: Mozilla Public License 2.0
#
# This software is distributed under the MPL-2.0 license.
# the text of which is available at https://www.mozilla.org/en-US/MPL/2.0/
# or see the "LICENSE" file for more details.

---
formatter: "markdown table"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false

sections:
  hide: ["providers"]

content: |-
  {{ .Header }}

  # Cloudavenue EdgeGateway Service Terraform Module

  This Terraform module is designed to manage services on a Cloudavenue Edge Gateway. It provides a simple and flexible way to configure and enable specific services, such as administration and S3, on an edge gateway.

  Features:
   - **Edge Gateway Integration**: Attach services to a specified edge gateway using its unique ID.
   - **Firewall Configuration**: Supports multiple firewall modes (bypass, ignore, with create planned for future implementation).
   - **Service Management**: Enable or disable specific services through a customizable configuration.

  This module simplifies the management of edge gateway services, ensuring a streamlined and consistent configuration process.

  ## Example(s)

  ### Basic usage
  ```hcl
  module "services" {
    source          = "orange-cloudavenue/edgegateway-services/cloudavenue"
    edge_gateway_id = cloudavenue_edgegateway.example.id
  }
  ```

  ## Disable a service
  ```hcl
  module "services" {
    source          = "orange-cloudavenue/edgegateway-services/cloudavenue"
    edge_gateway_id = cloudavenue_edgegateway.example.id
    services = {
      administration = false
    }
  }

  ```

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Resources }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  default: true
  escape: true
  hide-empty: true
  html: false
  indent: 2
  lockfile: false
  required: true
  sensitive: true
  type: true
